### ISSUE TITLE
use .encode('utf-8') makes requests library add a new Content-Type Header

### ISSUE THREAD

**Issue by KodjoSuprem** [histrio/py-couchdb#10]
In Python 3 byte / str problem

requests/models
the folowing code tests `if isinstance(data, str) or isinstance(data, builtin_str) or hasattr(data, 'read'):`

    if files:
                (body, content_type) = self._encode_files(files, data)
            else:
                if data:
                    body = self._encode_params(data)
                    if isinstance(data, str) or isinstance(data, builtin_str) or hasattr(data, 'read'):
                        content_type = None
                    else:
                        content_type = 'application/x-www-form-urlencoded'

            self.prepare_content_length(body)

            # Add content-type if it wasn't explicitly provided.
            if (content_type) and (not 'content-type' in self.headers):
                self.headers['Content-Type'] = content_type

the self.headers dict will contain

    b'Content-Type' : b'application/json'
    'Content-Type' :  'application/x-www-form-urlencoded'

resulting a couchdb protocol error:

`{"error":"bad_content_type","reason":"Content-Type must be application/json"}`

**Comment by histrio** [comment]
@KodjoSuprem  This problem is still relevant?
