### ISSUE TITLE
all_docs raises excpetion if some documents are not found

### ISSUE THREAD

**Issue by bmihelac** [histrio/py-couchdb#38]
I would expect that not found items not to be present in list.
Failing testcase is on the way.

refs #36

**Comment by histrio** [comment]
Hello, Bojan. This problem is still relevant?

**Comment by histrio** [comment]
@bmihelac This problem is still relevant?

**Comment by krisb78** [comment]
I believe I fixed this in:

https://github.com/histrio/py-couchdb/commit/b49240eed98258690ad8e4d9b3247269f7e8c007

**Comment by bmihelac** [comment]
All tests pass now. Sorry for late reply.

**Comment by bmihelac** [comment]
Tests rebased for master.

**Comment by histrio** [comment]
Thanks, Bojan.
