### ISSUE TITLE
Couchapp support

### ISSUE THREAD

**Issue by beezz** [histrio/py-couchdb#48]
Hi,

I'm working on couchapp (design documents) support for this module. It's inspired by erica (https://github.com/benoitc/erica).

For now it's in *pycouchdb.app* module and CLI tool has signature like this:

```
$ python -m pycouchdb.app push -h
usage: python -m pycouchdb.app push [-h] [--url COUCHDB_URL] [--db DBNAME]
                                    [--create-db]
                                    [APPDIRS [APPDIRS ...]]

positional arguments:
  APPDIRS            List of directories holding your couchapps. Defaults to
                     all directories found in your current working directory.

optional arguments:
  -h, --help         show this help message and exit
  --url COUCHDB_URL  CouchDB url. Defaults to `http://localhost:5984/`. For
                     basic auth, use e.g.
                     `http://user:password@localhost:5984`.
  --db DBNAME        Database name. Database must exist and you must have
                     sufficient permissions to read/write design documents
                     from/to it. If omitted, name of parent directory will be
                     used.
  --create-db        Create database if it does not exist.
```

In the end it should have support for operations:

* push - push directory as couchapp
* clone - clone existing couchapp
* create - create couchapp from included template

Would you like this to be part of pycouchdb? If so, do you have any suggestions?

**Comment by niwibe** [comment]
Hi @beezz 

I think that is very interesting thing, but I'm currently not using couchdb, and I thinking in search a new maintainer for this package. 
In this situation is slightly complicated accept this, knowing that I don't have more time for maintain this package.

**Comment by beezz** [comment]
That's bad news. So I think you can close this issue. If you'll feel like working on this package again or you'll find someone else, just reopen it.

**Comment by niwibe** [comment]
I'm still maintaingin the package, until new maintainer is found. But I don't want accept new features.
