### ISSUE TITLE
updated version on PyPI?

### ISSUE THREAD

**Issue by lullis** [histrio/py-couchdb#50]
Hey. First of all I'd like to thank you on the work on the library.

Now, I installed pycouchdb through PyPI and I was looking for a way to get the _db_updates feed. The PyPI latest version (1.12) does not provide this functionality. Because this functionality is needed for my current project, I went on to create a fork and see how I could implement it myself. I then realized that it is already available on the repo.

My question then would be: is there anything stopping to release a new version with this feature? Missing documentation? Tests? It would be really good to get this released, and I'd be glad to help.

**Comment by histrio** [comment]
Hi, Lullis.  Sure, I will release a new version as soon as I can.

**Comment by histrio** [comment]
Hi @lullis,
Sorry for late answer. I had one blocking issue before I can release a new version.

**Comment by histrio** [comment]
Done!
