### ISSUE TITLE
KeyError: 'etag' due to Bad Request v1.12

### ISSUE THREAD

**Issue by sandrobusonera** [histrio/py-couchdb#58]
Good Morning,

I just received this error:

```
py2.7.egg/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'etag'
```

After some investigation I found it was due to a bad request (wrong couchdb url, I forgot to put https instead of http):

```
(Pdb) resource.__dict__
{'session': <requests.sessions.Session object at 0x104283bd0>, 'base_url': 'XXX'}
(Pdb) resource.head()
(<Response [400]>, None)
```

This might be due to: if the result is none it returns the bad request and none: https://github.com/histrio/py-couchdb/blob/master/pycouchdb/resource.py#L101

I know that the mistake is mine but would it be more preferable for the system to throw an exception such as Bad Request (in that case at least)? https://github.com/histrio/py-couchdb/blob/master/pycouchdb/exceptions.py#L32

Many thanks

**Comment by histrio** [comment]
Thanks for bug report! I'll see what I can do.

-----Original Message-----

**Comment by sandrobusonera** [comment]
not sure if this was ever fixed. closing
