### ISSUE TITLE
package import on install

### ISSUE THREAD

**Issue by vangheem** [histrio/py-couchdb#59]
https://github.com/histrio/py-couchdb/blob/master/setup.py#L10 eventually causes an import of the requests library which can not be installed until  the setup function is called and can read the install_requires value. 

Just need to duplicate the version value or read from a shared file in the package to get around this problem.

**Comment by flyte** [comment]
Sorry to comment on a closed issue, but have a look at [bumpversion](https://github.com/peritus/bumpversion), which can handle the version updates in multiple places if needs be. I find it very useful :)

**Comment by histrio** [comment]
Hi @flyte !
Nice! It will help.
