### ISSUE TITLE
Incorrect urljoin when getting couchdb user

### ISSUE THREAD

**Issue by mhora** [histrio/py-couchdb#61]
It appears that replacing urljoin by urllib.parse.urljoin causes a problem when getting a user from couchdb. I have found that it is caused by urllib handling the colon in typical user id e.g. org.couchdb.user:username

```
>>> from urlparse import urljoin
>>> urljoin('http://example.com', 'org.couchdb.user:username')
'org.couchdb.user:username'
```

The same applies to python 3.x

This leads to 
```
requests.exceptions.InvalidSchema: No connection adapters were found for 'org.couchdb.user:username'
```

To me it looks like urllib problem as I would say a colon is an allowed character.

**Comment by histrio** [comment]
@mhora 
Thanks for bug report.  I'll fix it as soon as I can.

**Comment by mhora** [comment]
Thanks a lot for such a quick action
